version: 0.2

version: 0.2
env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-17-amazon-corretto/"
phases:
    install:
      runtime-versions:
        java: corretto17
    build:
      commands:
        - echo Build started on `date` 
        - mvn clean package
    post_build:
      commands:
        - echo Build completed on `date`
artifacts:
  files:
    - target/candidateprofile-0.0.1-SNAPSHOT.jar